spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        foramt_sql: true
  data:
    mongodb:
      uri: mongodb+srv://minsue9608:todnxksekd19!@mongocluster.7j9kmgm.mongodb.net/dream?retryWrites=true&w=majority&appName=mongoCluster
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true